name: netglade_flutter_utils
resolution: workspace
description: Flutter utils used internally at netglade.
version: 1.4.0
repository: https://github.com/netglade/flutter_core/tree/main/packages/netglade_flutter_utils
issue_tracker: https://github.com/netglade/flutter_core/issues
homepage: https://github.com/netglade/flutter_core
documentation: https://github.com/netglade/flutter_core/tree/main/packages/netglade_flutter_utils

environment:
  sdk: ^3.10.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  netglade_analysis: ^21.0.0
  test: ^1.25.8

flutter:
  uses-material-design: true
