name: netglade_analysis
version: 18.0.0
description: Lint rules for Dart and Flutter used internally at netglade.
repository: https://github.com/netglade/flutter_core/tree/main/packages/netglade_analysis
issue_tracker: https://github.com/netglade/flutter_core/issues
homepage: https://github.com/netglade/flutter_core
documentation: https://github.com/netglade/flutter_core/tree/main/packages/netglade_analysis
screenshots:
  - description: The netglade_analysis package logo.
    path: doc/icon.png

environment:
  sdk: ^3.8.0
resolution: workspace
