name: netglade_utils
resolution: workspace
description: Dart utils used internally at netglade.
version: 2.6.0
repository: https://github.com/netglade/flutter_core/tree/main/packages/netglade_utils
issue_tracker: https://github.com/netglade/flutter_core/issues
homepage: https://github.com/netglade/flutter_core
documentation: https://github.com/netglade/flutter_core/tree/main/packages/netglade_utils

environment:
  sdk: ^3.10.0

dependencies:
  characters: ^1.2.0
  clock: ^1.0.0
  collection: ^1.0.0
  http: ^1.0.0
  mocktail: ^1.0.0

dev_dependencies:
  netglade_analysis: ^21.0.0
  test: ^1.25.2
