name: netglade_flutter_utils_example
resolution: workspace
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  netglade_analysis: ^19.0.0
  netglade_flutter_utils:
    path: ..

flutter:
  uses-material-design: true
